#!/bin/bash
re='^[0-9]+$'
SINKS=$()

if [ -z ${1+x} ]; then
    SINKS=$(pactl list sinks short | sed -En 's/([0-9]+).*$/\1/p')
else
    SINKS=$(pactl list sinks | sed -En '/Sink #'$(cat /tmp/pactl-volumectl-sink)'/,/(Sink #[0-9]+)/ s/^\s*Description: (.*)$/\1/p')
fi

echo -e "$SINKS"